import argparse as ap

parser = ap.ArgumentParser()
parser.add_argument("py_command", help="The python command to be run", type=str)
parser.add_argument("memory", help="Memory to be allocated", type=int)
parser.add_argument("location", help="Location to which the outputs will be saved")
args = parser.parse_args()

script_file = open("run.sh", 'w')
script_file.write('#!/bin/sh\n')
script_file.write('#$ -S /bin/sh\n')
script_file.write('#$ -o %s\n' % args.location)
script_file.write('#$ -e %s\n' % args.location)
script_file.write('#$ -M haranrk@hgc.jp\n')
script_file.write('#$ -m bae\n')
script_file.write('#$ -N depmap\n')
script_file.write('#$ -cwd -j y -l ljob -l s_vmem=%iG -l mem_req=%iG\n' % (args.memory, args.memory))
script_file.write('echo "START: " `date  "+%Y%m%d-%H%M%S"`\n')
script_file.write('start_time=`date +%s`\n')
script_file.write('module load python/3.6.4\n')
script_file.write(args.py_command+'\n')
script_file.write('echo "DONE: " `date  "+%Y%m%d-%H%M%S"`\n')
script_file.write('end_time=`date +%s`\n')
script_file.write('duration=$((end_time - start_time))\n')
script_file.write('echo "TIME: " $duration\n')
script_file.close()